#!/bin/bash -e

export HOME=/home/melpa
cd ${HOME}/melpa

# Build all the packages.
scripts/parallel_build_all

echo '{"completed":' `date "+%s"` '}' > /home/melpa/www/build-status.json

# Sleep for an hour before rebuilding.
sleep 1h
